name: Markdown Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
            # https://github.com/actions/setup-node
            - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903

            - name: Install CLI for markdownlint
              run: npm install markdownlint-cli2@0.18.1 --global

            - name: Lint Markdown files, while excluding anything under the node_modules directories
              run: markdownlint-cli2 "**/*.md" "#node_modules"
